### ISSUE TITLE
The daily tests (Scheduled UW IdP Test Matrix) are not running, please fix. 

### ISSUE THREAD

**Issue by goulter** [UWIT-IAM/uw-idp-web-tests#35]
Ah, the culprit is/was `setup-gcloud`.

**Comment by jdiverp** [comment]
Adding a note about the changes I made.. Web SSL certificates on the diafineX.sandbox.iam.s.uw.edu  were expired. I copied the cert and key from certbot into IIS to make the web servers this software touches work again.
